// Theme system single source (U-themes): scripts/theme-source.json is the
// only place theme color tokens are authored. This script derives any
// missing `--color-on-X-container` tokens, validates every theme against
// the shared AA pair contract (scripts/lib/contrast.mjs), and emits:
//   src/theme/generated/themes.css    — default `@theme` + one [data-theme] block per theme
//   src/theme/generated/registry.ts   — the theme id → light/dark scheme map
//
// Usage: node scripts/generate-themes.mjs [--check]
//   --check  exits 1 when the committed generated files differ from what
//            the source would produce (CI drift tripwire).
// Exit code 1 on derivation failure, AA failure, or (--check) drift.

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'
import { auditThemes, contrast } from './lib/contrast.mjs'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const source = JSON.parse(readFileSync(join(root, 'scripts', 'theme-source.json'), 'utf8'))
const outDir = join(root, 'src', 'theme', 'generated')
mkdirSync(outDir, { recursive: true })

// ── Derivation ──────────────────────────────────────────────────────────────
// A theme may declare `--color-X-container` without `--color-on-X-container`
// (this is how every dark theme originally shipped — inheriting the light
// base's dark-red on-error-container at ~1.3:1). Derive the on-token from
// the container color: a tint of the container itself (hue-preserving), only
// kept if it clears AA 4.5:1 — otherwise the generation FAILS loudly rather
// than shipping an inaccessible pair.
function mixOntoWhite(hex, keep = 0.14) {
  const ch = [1, 3, 5].map(i => parseInt(hex.slice(i, i + 2), 16))
  const mixed = ch.map(c => Math.round(255 - (255 - c) * keep))
  return '#' + mixed.map(c => c.toString(16).padStart(2, '0')).join('')
}
function mixOntoBlack(hex, keep = 0.14) {
  const ch = [1, 3, 5].map(i => parseInt(hex.slice(i, i + 2), 16))
  const mixed = ch.map(c => Math.round(c * keep))
  return '#' + mixed.map(c => c.toString(16).padStart(2, '0')).join('')
}

const derivedReport = []
for (const [id, theme] of Object.entries(source.themes)) {
  const vars = theme.vars
  for (const name of Object.keys(vars)) {
    // `(?!on-)` — `--color-on-primary-container` already IS an on-token.
    const m = /^--color-(?!on-)([\w-]+)-container$/.exec(name)
    if (!m) continue
    const onName = `--color-on-${m[1]}-container`
    // Last-resort only: skip when the theme block OR the base palette
    // already supplies the token (a theme inheriting base's value via the
    // cascade must not get silently overridden by a derived tint).
    if (vars[onName] || source.base[onName]) continue
    const bg = vars[name]
    const bgLuminance = (() => {
      const [r, g, b] = [1, 3, 5].map(i => parseInt(bg.slice(i, i + 2), 16) / 255)
      return 0.2126 * r + 0.7152 * g + 0.0722 * b
    })()
    const candidate = bgLuminance >= 0.5 ? mixOntoBlack(bg) : mixOntoWhite(bg)
    if (contrast(candidate, bg) < 4.5) {
      console.error(`generate-themes: ${id}: cannot derive ${onName} for ${bg} (no AA candidate)`)
      process.exit(1)
    }
    vars[onName] = candidate
    derivedReport.push(`${id}: ${onName} ← derived from ${bg}`)
  }
}

// ── Validate against the AA pair contract ───────────────────────────────────
const auditInput = {}
for (const [id, theme] of Object.entries(source.themes)) {
  auditInput[id] = { ...source.base, ...theme.vars }
}
auditInput.material = { ...auditInput.material } // base ⊂ material by construction
const failures = auditThemes(auditInput)
if (failures.length > 0) {
  console.error('generate-themes: AA pair contract FAILED:')
  for (const f of failures) {
    console.error(
      `  ${f.theme}: ${f.ratio.toFixed(2)}:1 (min ${f.min}) ${f.fg} on ${f.bg} — ${f.label} [${f.fgValue} on ${f.bgValue}]`,
    )
  }
  process.exit(1)
}

// ── Emit themes.css (per-theme overrides only — plain custom properties,
// no @theme: Vite dev does not run the Tailwind plugin on @import'ed css,
// so a @theme block there would be served verbatim and ignored) ─────────────
function emitVars(vars, indent = '  ') {
  // Blank-line groups mirroring the authored layout: shadcn names first,
  // then MD3 `--color-*` / chart tokens, preserving source order.
  const entries = Object.entries(vars)
  const lines = []
  let prevWasShadcn = null
  for (const [name, value] of entries) {
    const isShadcn = !name.startsWith('--color-') && !name.startsWith('--chart-')
    if (prevWasShadcn === true && !isShadcn) lines.push('')
    lines.push(`${indent}${name}: ${value};`)
    prevWasShadcn = isShadcn
  }
  return lines.join('\n')
}

const cssParts = []
cssParts.push(
  '/* GENERATED by scripts/generate-themes.mjs from scripts/theme-source.json —',
  '   do not edit by hand. Run `pnpm generate:themes` after editing the source.',
  '   The base palette lives in index.css\'s GENERATED:THEME_BASE region (the',
  '   @theme block must stay in the entry stylesheet for Tailwind to see it). */',
)
for (const [id, theme] of Object.entries(source.themes)) {
  const selector = id === 'material' ? ':root,\n[data-theme=\'material\']' : `[data-theme='${id}']`
  cssParts.push(
    '',
    ...(theme.comment ? [`/* ${theme.comment} */`] : []),
    `${selector} {`,
    emitVars(theme.vars),
    '}',
  )
}
const css = cssParts.join('\n') + '\n'

// ── Emit registry.ts ────────────────────────────────────────────────────────
const registryLines = Object.entries(source.themes).map(
  ([id, theme]) => `  { id: '${id}', mode: '${theme.mode}' },`,
)
const registryTs = `// GENERATED by scripts/generate-themes.mjs from scripts/theme-source.json —
// do not edit by hand. ThemeContext derives THEME_SCHEMES (the light/dark
// scheme each resolved theme renders as) from this list. \`as const\` keeps
// the ids as literal types so ThemeContext's compile-time drift check works.
export const THEME_REGISTRY = [
${registryLines.join('\n')}
] as const
`

// ── Inject the base palette into index.css's generated region ───────────────
const INDEX_START = '/* GENERATED:THEME_BASE:START */'
const INDEX_END = '/* GENERATED:THEME_BASE:END */'
const indexPath = join(root, 'src', 'index.css')
const indexCss = readFileSync(indexPath, 'utf8')
const startIndex = indexCss.indexOf(INDEX_START)
const endIndex = indexCss.indexOf(INDEX_END)
if (startIndex === -1 || endIndex === -1 || startIndex > endIndex) {
  console.error(`generate-themes: ${INDEX_START}/${INDEX_END} markers missing from src/index.css`)
  process.exit(1)
}
const baseRegion = INDEX_START + '\n' + emitVars(source.base) + '\n  ' + INDEX_END
const newIndexCss = indexCss.slice(0, startIndex) + baseRegion + indexCss.slice(endIndex + INDEX_END.length)

// ── Write (or verify with --check) ──────────────────────────────────────────
const cssPath = join(outDir, 'themes.css')
const registryPath = join(outDir, 'registry.ts')
const check = process.argv.includes('--check')
let drifted = false
for (const [path, content] of [[cssPath, css], [registryPath, registryTs], [indexPath, newIndexCss]]) {
  const existing = (() => { try { return readFileSync(path, 'utf8') } catch { return null } })()
  if (existing !== content) {
    if (check) {
      console.error(`generate-themes: --check: ${path} is stale — run \`pnpm generate:themes\``)
      drifted = true
    } else {
      writeFileSync(path, content)
      console.log(`generate-themes: wrote ${path}`)
    }
  }
}
if (drifted) process.exit(1)
for (const line of derivedReport) console.log(`generate-themes: derived ${line}`)
console.log(`generate-themes: ${Object.keys(source.themes).length} themes, AA pair contract passed${check ? ' (no drift)' : ''}`)
