#!/usr/bin/env bash
# move-semver-baseline.sh — automate the semver-baseline tag move that
# ci.yml's SEMVER_BASELINE requires after every intentional minor-cycle
# break (the numbered "moves" in .github/workflows/ci.yml).
#
# Manual procedure before this script (15 moves as of PR #116):
#   1. pick the next semver-baseline-YYYY-MM-<n> tag name,
#   2. rewrite SEMVER_BASELINE in ci.yml,
#   3. commit, tag HEAD, push branch + tag (new name invalidates the
#      baseline-rustdoc cache via prefix-key).
#
# Usage: bash scripts/move-semver-baseline.sh ["reason for the move"]
# Run from a branch that contains the breaking changes; the tag points at
# the commit this script creates.
set -euo pipefail

REASON="${1:-intentional minor-cycle break}"
CI_FILE=".github/workflows/ci.yml"

command -v git >/dev/null || { echo "git required" >&2; exit 1; }
[ -f "${CI_FILE}" ] || { echo "run from the repo root" >&2; exit 1; }

# 1. Next tag name: same YYYY-MM, increment the sequence number.
CURRENT="$(sed -n 's/^      SEMVER_BASELINE: \(.*\)$/\1/p' "${CI_FILE}" | tail -1)"
[ -n "${CURRENT}" ] || { echo "SEMVER_BASELINE not found in ${CI_FILE}" >&2; exit 1; }
DATE_PART="${CURRENT%-*}"
SEQ="${CURRENT##*-}"
case "${SEQ}" in (*[!0-9]*|"") echo "cannot parse sequence from ${CURRENT}" >&2; exit 1;; esac
NEXT="${DATE_PART}-$((SEQ + 1))"
if git rev-parse -q --verify "refs/tags/${NEXT}" >/dev/null; then
  echo "tag ${NEXT} already exists — pick the next number manually" >&2
  exit 1
fi

# 2. Rewrite SEMVER_BASELINE (prefix-key derives from the same env var).
sed -i "s|^      SEMVER_BASELINE: .*|      SEMVER_BASELINE: ${NEXT}|" "${CI_FILE}"
grep -q "SEMVER_BASELINE: ${NEXT}" "${CI_FILE}" || { echo "rewrite failed" >&2; exit 1; }

# 3. Commit, tag HEAD, push branch + tag.
git add "${CI_FILE}"
git commit -m "ci: move semver baseline to ${NEXT}

${REASON}
Intentional minor-cycle break; new TAG NAME so the baseline-rustdoc
cache invalidates. (Generated by scripts/move-semver-baseline.sh.)"
git tag -a "${NEXT}" -m "Semver baseline: ${REASON}"
echo "Pushing branch and tag ${NEXT}..."
git push
git push origin "refs/tags/${NEXT}"
echo "Done. Baseline moved: ${CURRENT} -> ${NEXT}"
