//! Tool Use Summary
//!
//! Generates human-readable summaries of completed tool batches.
//! Produces git-commit-style short labels like "Fixed NPE in UserService".
//!
//! Supports both rule-based summary generation and optional AI-powered
//! summarization via a configurable model endpoint.

use serde::{Deserialize, Serialize};
use serde_json::Value;
use std::future::Future;
use std::pin::Pin;

/// Information about a completed tool call
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ToolUseInfo {
    pub name: String,
    pub input: Value,
    pub output: Value,
}

/// Summary generation result
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ToolUseSummary {
    pub label: String,
    pub tools_processed: usize,
}

/// Configuration for AI-powered summary generation.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AiSummaryConfig {
    /// Whether AI summarization is enabled.
    pub enabled: bool,
    /// The model to use for summarization (e.g., "claude-haiku-4-5").
    pub model: String,
    /// Maximum length of the generated summary label.
    pub max_summary_length: usize,
}

impl Default for AiSummaryConfig {
    fn default() -> Self {
        Self {
            enabled: false,
            model: "claude-haiku-4-5".to_string(),
            max_summary_length: 80,
        }
    }
}

impl AiSummaryConfig {
    /// Create a new AI summary configuration with sensible defaults.
    pub fn new(model: impl Into<String>) -> Self {
        Self {
            enabled: true,
            model: model.into(),
            max_summary_length: 80,
        }
    }

    /// Enable or disable AI summarization.
    pub fn with_enabled(mut self, enabled: bool) -> Self {
        self.enabled = enabled;
        self
    }

    /// Set the maximum summary label length.
    pub fn with_max_length(mut self, max_len: usize) -> Self {
        self.max_summary_length = max_len;
        self
    }
}

/// The source of a generated summary.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum SummarySource {
    /// Generated by rule-based pattern matching.
    RuleBased,
    /// Generated by an AI model.
    AiGenerated,
}

/// Enhanced summary that tracks its source.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EnhancedToolUseSummary {
    /// The summary label.
    pub label: String,
    /// How many tools were summarized.
    pub tools_processed: usize,
    /// Whether this came from rules or AI.
    pub source: SummarySource,
}

impl From<ToolUseSummary> for EnhancedToolUseSummary {
    fn from(s: ToolUseSummary) -> Self {
        Self {
            label: s.label,
            tools_processed: s.tools_processed,
            source: SummarySource::RuleBased,
        }
    }
}

/// Generator for tool use summaries.
///
/// Supports both rule-based generation (always available) and optional
/// AI-powered summarization for higher-quality labels.
pub struct ToolUseSummaryGenerator {
    ai_config: Option<AiSummaryConfig>,
}

impl Default for ToolUseSummaryGenerator {
    fn default() -> Self {
        Self::new()
    }
}

type ApiClientFn =
    dyn Fn(String) -> Pin<Box<dyn Future<Output = Result<String, Box<dyn std::error::Error>>>>>;

impl ToolUseSummaryGenerator {
    pub fn new() -> Self {
        Self { ai_config: None }
    }

    /// Configure AI-powered summary generation.
    pub fn with_ai_config(mut self, config: AiSummaryConfig) -> Self {
        self.ai_config = Some(config);
        self
    }

    /// Check if AI summarization is configured and enabled.
    pub fn ai_enabled(&self) -> bool {
        self.ai_config.as_ref().map(|c| c.enabled).unwrap_or(false)
    }

    /// Generate a short summary label for a batch of tool calls using rules.
    ///
    /// This is the fast, deterministic path that always works without an API call.
    pub fn generate(&self, tools: &[ToolUseInfo]) -> Option<ToolUseSummary> {
        if tools.is_empty() {
            return None;
        }

        let _actions: Vec<String> = tools
            .iter()
            .map(|tool| {
                let input_summary = summarize_value(&tool.input, 100);
                format!("{}({})", tool.name, input_summary)
            })
            .collect();

        // Generate a git-commit-style label
        let label = self.generate_label(tools);

        Some(ToolUseSummary {
            label,
            tools_processed: tools.len(),
        })
    }

    /// Generate a summary using rule-based logic.
    ///
    /// Returns an enhanced summary with source tracking.
    pub fn generate_enhanced(&self, tools: &[ToolUseInfo]) -> Option<EnhancedToolUseSummary> {
        self.generate(tools).map(Into::into)
    }

    /// Generate a summary using AI-powered summarization.
    ///
    /// The `api_client` parameter is a closure that sends a prompt to the AI model
    /// and returns the response text. This allows callers to inject their own
    /// HTTP client or mock for testing.
    ///
    /// If AI is not configured, returns `None`.
    /// If the API call fails, falls back to rule-based generation.
    pub async fn generate_ai_summary(
        &self,
        tools: &[ToolUseInfo],
        api_client: &ApiClientFn,
    ) -> Option<EnhancedToolUseSummary> {
        // Check if AI is enabled
        if !self.ai_enabled() {
            return self.generate_enhanced(tools);
        }

        if tools.is_empty() {
            return None;
        }

        let config = match self.ai_config.as_ref() {
            Some(c) => c,
            None => return self.generate_enhanced(tools),
        };
        let prompt = self.build_ai_prompt(tools);

        // Attempt AI generation
        match api_client(prompt).await {
            Ok(response) => {
                let label = self.parse_ai_response(&response, config.max_summary_length);
                Some(EnhancedToolUseSummary {
                    label,
                    tools_processed: tools.len(),
                    source: SummarySource::AiGenerated,
                })
            }
            Err(e) => {
                tracing::warn!("AI summary generation failed, falling back to rules: {}", e);
                self.generate_enhanced(tools)
            }
        }
    }

    /// Build a prompt for the AI model to generate a summary.
    ///
    /// The prompt describes the tool calls and asks for a concise label.
    fn build_ai_prompt(&self, tools: &[ToolUseInfo]) -> String {
        let tool_descriptions: Vec<String> = tools
            .iter()
            .map(|tool| {
                let input_summary = summarize_value(&tool.input, 200);
                let output_summary = if tool.output.is_null()
                    || tool.output.as_object().is_none_or(|o| o.is_empty())
                {
                    String::new()
                } else {
                    let s = summarize_value(&tool.output, 100);
                    format!(" -> {s}")
                };
                format!("- {}: {}{}", tool.name, input_summary, output_summary)
            })
            .collect();

        let config = match self.ai_config.as_ref() {
            Some(c) => c,
            None => return String::new(),
        };

        format!(
            "Generate a concise git-commit-style summary label (max {} chars) for these tool calls. \
             Only output the label text, nothing else. \
             Use imperative mood (e.g., \"Fixed NPE\", \"Added tests\", \"Refactored auth module\").\n\n\
             Tool calls:\n{}",
            config.max_summary_length,
            tool_descriptions.join("\n")
        )
    }

    /// Parse the AI response into a clean summary label.
    ///
    /// Strips markdown formatting, quotes, and whitespace.
    /// Truncates to the configured max length if needed.
    fn parse_ai_response(&self, response: &str, max_length: usize) -> String {
        let label = response
            .lines()
            .next()
            .unwrap_or(response)
            .trim()
            // Strip markdown code fences
            .trim_start_matches("```")
            .trim_end_matches("```")
            .trim()
            // Strip surrounding quotes
            .trim_start_matches('"')
            .trim_end_matches('"')
            .trim_start_matches('\'')
            .trim_end_matches('\'')
            .to_string();

        if label.len() <= max_length {
            label
        } else {
            // Truncate at word boundary if possible
            let mut truncated = label[..max_length - 3].to_string();
            if let Some(space_pos) = truncated.rfind(' ') {
                truncated.truncate(space_pos);
            }
            format!("{truncated}...")
        }
    }

    fn generate_label(&self, tools: &[ToolUseInfo]) -> String {
        let tool_names: Vec<&str> = tools.iter().map(|t| t.name.as_str()).collect();

        // Pattern matching for common operations
        match tool_names.as_slice() {
            [name] if name.contains("Read") || name.contains("Glob") || name.contains("Grep") => {
                let target = extract_target(&tools[0].input);
                format!("Searched in {target}")
            }
            [name] if name.contains("Write") || name.contains("Edit") => {
                let target = extract_target(&tools[0].input);
                format!("Modified {target}")
            }
            [name] if name.contains("Bash") => {
                let cmd = tools[0]
                    .input
                    .get("command")
                    .and_then(|v| v.as_str())
                    .unwrap_or("unknown");
                let truncated = cmd.chars().take(50).collect::<String>();
                format!("Ran: {truncated}")
            }
            _ => {
                let primary = tool_names.first().unwrap_or(&"Tool");
                format!("{} ({} calls)", primary, tools.len())
            }
        }
    }
}

/// Extract a file path target from tool input.
/// Shows the full path from the input for clarity.
fn extract_target(input: &Value) -> String {
    input
        .get("file_path")
        .or_else(|| input.get("path"))
        .or_else(|| input.get("pattern"))
        .and_then(|v| v.as_str())
        .map(|s| s.to_string())
        .unwrap_or_else(|| "files".to_string())
}

/// Summarize a JSON value to a short string
fn summarize_value(value: &Value, max_len: usize) -> String {
    let s = serde_json::to_string(value).unwrap_or_else(|_| "[complex]".to_string());
    if s.len() <= max_len {
        s
    } else {
        format!("{}...", &s[..max_len - 3])
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    fn make_tool(name: &str, input: Value) -> ToolUseInfo {
        ToolUseInfo {
            name: name.to_string(),
            input,
            output: json!({}),
        }
    }

    fn make_tool_with_output(name: &str, input: Value, output: Value) -> ToolUseInfo {
        ToolUseInfo {
            name: name.to_string(),
            input,
            output,
        }
    }

    // ── Existing rule-based tests ──────────────────────────────────────

    #[test]
    fn test_empty_tools() {
        let generator = ToolUseSummaryGenerator::new();
        assert!(generator.generate(&[]).is_none());
    }

    #[test]
    fn test_read_tool() {
        let generator = ToolUseSummaryGenerator::new();
        let tools = vec![make_tool("Read", json!({"file_path": "src/main.rs"}))];
        let summary = generator.generate(&tools).unwrap();
        assert_eq!(summary.label, "Searched in src/main.rs");
        assert_eq!(summary.tools_processed, 1);
    }

    #[test]
    fn test_edit_tool() {
        let generator = ToolUseSummaryGenerator::new();
        let tools = vec![make_tool(
            "Edit",
            json!({"file_path": "src/lib.rs", "old_string": "foo", "new_string": "bar"}),
        )];
        let summary = generator.generate(&tools).unwrap();
        assert_eq!(summary.label, "Modified src/lib.rs");
    }

    #[test]
    fn test_bash_tool() {
        let generator = ToolUseSummaryGenerator::new();
        let tools = vec![make_tool(
            "Bash",
            json!({"command": "cargo test --workspace"}),
        )];
        let summary = generator.generate(&tools).unwrap();
        assert!(summary.label.starts_with("Ran:"));
    }

    #[test]
    fn test_multiple_tools() {
        let generator = ToolUseSummaryGenerator::new();
        let tools = vec![
            make_tool("Read", json!({"file_path": "src/main.rs"})),
            make_tool("Edit", json!({"file_path": "src/main.rs"})),
            make_tool("Bash", json!({"command": "cargo check"})),
        ];
        let summary = generator.generate(&tools).unwrap();
        assert!(summary.label.contains("Read"));
        assert_eq!(summary.tools_processed, 3);
    }

    #[test]
    fn test_nested_path() {
        let generator = ToolUseSummaryGenerator::new();
        let tools = vec![make_tool(
            "Read",
            json!({"file_path": "crates/shannon-core/src/lib.rs"}),
        )];
        let summary = generator.generate(&tools).unwrap();
        assert!(summary.label.contains("crates/shannon-core/src/lib.rs"));
    }

    // ── AiSummaryConfig tests ──────────────────────────────────────────

    #[test]
    fn test_ai_config_default() {
        let config = AiSummaryConfig::default();
        assert!(!config.enabled);
        assert_eq!(config.model, "claude-haiku-4-5");
        assert_eq!(config.max_summary_length, 80);
    }

    #[test]
    fn test_ai_config_new() {
        let config = AiSummaryConfig::new("gpt-4");
        assert!(config.enabled);
        assert_eq!(config.model, "gpt-4");
    }

    #[test]
    fn test_ai_config_builder() {
        let config = AiSummaryConfig::new("claude-haiku-4-5")
            .with_enabled(false)
            .with_max_length(120);
        assert!(!config.enabled);
        assert_eq!(config.max_summary_length, 120);
    }

    #[test]
    fn test_ai_config_serialization() {
        let config = AiSummaryConfig::new("claude-haiku-4-5").with_max_length(100);
        let json_str = serde_json::to_string(&config).unwrap();
        let parsed: AiSummaryConfig = serde_json::from_str(&json_str).unwrap();
        assert_eq!(parsed.model, "claude-haiku-4-5");
        assert_eq!(parsed.max_summary_length, 100);
        assert!(parsed.enabled);
    }

    // ── EnhancedToolUseSummary tests ───────────────────────────────────

    #[test]
    fn test_enhanced_summary_from_basic() {
        let basic = ToolUseSummary {
            label: "Searched in src/main.rs".to_string(),
            tools_processed: 1,
        };
        let enhanced: EnhancedToolUseSummary = basic.into();
        assert_eq!(enhanced.label, "Searched in src/main.rs");
        assert_eq!(enhanced.source, SummarySource::RuleBased);
    }

    #[test]
    fn test_generate_enhanced_rule_based() {
        let generator = ToolUseSummaryGenerator::new();
        let tools = vec![make_tool("Read", json!({"file_path": "a.rs"}))];
        let summary = generator.generate_enhanced(&tools).unwrap();
        assert_eq!(summary.source, SummarySource::RuleBased);
        assert_eq!(summary.tools_processed, 1);
    }

    #[test]
    fn test_generate_enhanced_empty() {
        let generator = ToolUseSummaryGenerator::new();
        assert!(generator.generate_enhanced(&[]).is_none());
    }

    // ── ToolUseSummaryGenerator with AI config ─────────────────────────

    #[test]
    fn test_generator_with_ai_config() {
        let generator =
            ToolUseSummaryGenerator::new().with_ai_config(AiSummaryConfig::new("claude-haiku-4-5"));
        assert!(generator.ai_enabled());
    }

    #[test]
    fn test_generator_without_ai_config() {
        let generator = ToolUseSummaryGenerator::new();
        assert!(!generator.ai_enabled());
    }

    #[test]
    fn test_generator_with_disabled_ai_config() {
        let generator = ToolUseSummaryGenerator::new()
            .with_ai_config(AiSummaryConfig::new("claude-haiku-4-5").with_enabled(false));
        assert!(!generator.ai_enabled());
    }

    #[tokio::test]
    async fn test_ai_summary_fallback_on_error() {
        let generator =
            ToolUseSummaryGenerator::new().with_ai_config(AiSummaryConfig::new("claude-haiku-4-5"));

        let tools = vec![make_tool("Read", json!({"file_path": "src/main.rs"}))];

        let error_client = |_prompt: String| -> Pin<
            Box<dyn Future<Output = Result<String, Box<dyn std::error::Error>>>>,
        > { Box::pin(async { Err("API error".into()) }) };

        let summary = generator
            .generate_ai_summary(&tools, &error_client)
            .await
            .unwrap();
        // Should fall back to rule-based
        assert_eq!(summary.source, SummarySource::RuleBased);
        assert_eq!(summary.tools_processed, 1);
    }

    #[tokio::test]
    async fn test_ai_summary_uses_api_response() {
        let generator =
            ToolUseSummaryGenerator::new().with_ai_config(AiSummaryConfig::new("claude-haiku-4-5"));

        let tools = vec![make_tool("Edit", json!({"file_path": "src/lib.rs"}))];

        let success_client = |_prompt: String| -> Pin<
            Box<dyn Future<Output = Result<String, Box<dyn std::error::Error>>>>,
        > {
            Box::pin(async { Ok("Fixed authentication bug".to_string()) })
        };

        let summary = generator
            .generate_ai_summary(&tools, &success_client)
            .await
            .unwrap();
        assert_eq!(summary.source, SummarySource::AiGenerated);
        assert_eq!(summary.label, "Fixed authentication bug");
        assert_eq!(summary.tools_processed, 1);
    }

    #[tokio::test]
    async fn test_ai_summary_empty_tools() {
        let generator =
            ToolUseSummaryGenerator::new().with_ai_config(AiSummaryConfig::new("claude-haiku-4-5"));

        let client = |_prompt: String| -> Pin<
            Box<dyn Future<Output = Result<String, Box<dyn std::error::Error>>>>,
        > { Box::pin(async { Ok("should not be called".to_string()) }) };

        let result = generator.generate_ai_summary(&[], &client).await;
        assert!(result.is_none());
    }

    #[tokio::test]
    async fn test_ai_summary_not_enabled_falls_back() {
        let generator = ToolUseSummaryGenerator::new().with_ai_config(AiSummaryConfig::default()); // enabled: false

        let tools = vec![make_tool("Bash", json!({"command": "cargo test"}))];

        let client = |_prompt: String| -> Pin<
            Box<dyn Future<Output = Result<String, Box<dyn std::error::Error>>>>,
        > {
            Box::pin(async { panic!("Should not be called when AI is disabled") })
        };

        let summary = generator
            .generate_ai_summary(&tools, &client)
            .await
            .unwrap();
        assert_eq!(summary.source, SummarySource::RuleBased);
    }

    // ── AI prompt building tests ───────────────────────────────────────

    #[test]
    fn test_build_ai_prompt_includes_tool_info() {
        let generator = ToolUseSummaryGenerator::new()
            .with_ai_config(AiSummaryConfig::new("claude-haiku-4-5").with_max_length(60));

        let tools = vec![
            make_tool("Read", json!({"file_path": "src/main.rs"})),
            make_tool(
                "Edit",
                json!({"file_path": "src/main.rs", "old_string": "foo", "new_string": "bar"}),
            ),
        ];

        let prompt = generator.build_ai_prompt(&tools);
        assert!(prompt.contains("Read"));
        assert!(prompt.contains("src/main.rs"));
        assert!(prompt.contains("Edit"));
        assert!(prompt.contains("60 chars"));
        assert!(prompt.contains("git-commit-style"));
    }

    #[test]
    fn test_build_ai_prompt_includes_output() {
        let generator =
            ToolUseSummaryGenerator::new().with_ai_config(AiSummaryConfig::new("claude-haiku-4-5"));

        let tools = vec![make_tool_with_output(
            "Bash",
            json!({"command": "cargo test"}),
            json!({"stdout": "test result: ok", "exit_code": 0}),
        )];

        let prompt = generator.build_ai_prompt(&tools);
        assert!(prompt.contains("stdout"));
    }

    // ── AI response parsing tests ──────────────────────────────────────

    #[test]
    fn test_parse_ai_response_clean() {
        let generator = ToolUseSummaryGenerator::new().with_ai_config(AiSummaryConfig::new("test"));
        assert_eq!(
            generator.parse_ai_response("Fixed authentication bug", 80),
            "Fixed authentication bug"
        );
    }

    #[test]
    fn test_parse_ai_response_strips_code_fences() {
        let generator = ToolUseSummaryGenerator::new().with_ai_config(AiSummaryConfig::new("test"));
        assert_eq!(
            generator.parse_ai_response("```Fixed auth```", 80),
            "Fixed auth"
        );
    }

    #[test]
    fn test_parse_ai_response_strips_quotes() {
        let generator = ToolUseSummaryGenerator::new().with_ai_config(AiSummaryConfig::new("test"));
        assert_eq!(
            generator.parse_ai_response("\"Fixed auth bug\"", 80),
            "Fixed auth bug"
        );
    }

    #[test]
    fn test_parse_ai_response_truncates_long() {
        let generator = ToolUseSummaryGenerator::new().with_ai_config(AiSummaryConfig::new("test"));
        let long = "This is a very long summary that exceeds the maximum length";
        let result = generator.parse_ai_response(long, 20);
        assert!(result.len() <= 20);
        assert!(result.ends_with("..."));
    }

    #[test]
    fn test_parse_ai_response_multiline() {
        let generator = ToolUseSummaryGenerator::new().with_ai_config(AiSummaryConfig::new("test"));
        let response = "Fixed auth bug\n\nAdditional explanation here";
        assert_eq!(generator.parse_ai_response(response, 80), "Fixed auth bug");
    }

    #[test]
    fn test_parse_ai_response_whitespace() {
        let generator = ToolUseSummaryGenerator::new().with_ai_config(AiSummaryConfig::new("test"));
        assert_eq!(
            generator.parse_ai_response("  Fixed auth bug  ", 80),
            "Fixed auth bug"
        );
    }

    // ── SummarySource tests ────────────────────────────────────────────

    #[test]
    fn test_summary_source_serialization() {
        let source = SummarySource::RuleBased;
        let json = serde_json::to_string(&source).unwrap();
        let parsed: SummarySource = serde_json::from_str(&json).unwrap();
        assert_eq!(parsed, SummarySource::RuleBased);

        let source = SummarySource::AiGenerated;
        let json = serde_json::to_string(&source).unwrap();
        let parsed: SummarySource = serde_json::from_str(&json).unwrap();
        assert_eq!(parsed, SummarySource::AiGenerated);
    }

    // ── EnhancedToolUseSummary serialization ───────────────────────────

    #[test]
    fn test_enhanced_summary_serialization() {
        let summary = EnhancedToolUseSummary {
            label: "Fixed bug".to_string(),
            tools_processed: 3,
            source: SummarySource::AiGenerated,
        };
        let json = serde_json::to_string(&summary).unwrap();
        let parsed: EnhancedToolUseSummary = serde_json::from_str(&json).unwrap();
        assert_eq!(parsed.label, "Fixed bug");
        assert_eq!(parsed.tools_processed, 3);
        assert_eq!(parsed.source, SummarySource::AiGenerated);
    }

    #[test]
    fn test_generator_default() {
        let generator = ToolUseSummaryGenerator::default();
        assert!(!generator.ai_enabled());
        assert!(generator.generate(&[]).is_none());
    }
}
