# Homebrew Cask for Shannon Desktop.
# NOTE: This Cask is NOT auto-generated by cargo-dist — it is maintained by hand
# under the tap `shannon-agent/homebrew-shannon`.
# Asset URLs/versions are filled at release time (CI / `brew bump-cask-pr`).
# Replace `#{version}` and the architecture suffix at release time if needed.

cask "shannon-desktop" do
  version "0.7.0" # REPLACE AT RELEASE TIME — CI fills the real version.

  name "Shannon Desktop"
  desc "Desktop app for the Shannon Agent (shannon-desktop)"
  homepage "https://github.com/shannon-agent/shannon-agent"

  # macOS Intel disk image.
  url "https://github.com/shannon-agent/shannon-agent/releases/download/v#{version}/shannon-desktop_#{version}_x64.dmg"
  # macOS Apple Silicon variant (replace the file name at release time):
  # url "https://github.com/shannon-agent/shannon-agent/releases/download/v#{version}/shannon-desktop_#{version}_aarch64.dmg"

  # sha256 "" # REPLACE AT RELEASE TIME with the real sha256 of the .dmg asset.

  # Linux/Windows bundles for the same release (install via native package managers):
  #   Linux:   shannon-desktop_#{version}_amd64.deb / shannon-desktop-#{version}-1.x86_64.rpm
  #   Windows: shannon-desktop_#{version}_x64-setup.exe
  livecheck do
    url "https://github.com/shannon-agent/shannon-agent/releases/latest"
    regex(/v?(\d+(?:\.\d+)+)/i)
  end

  depends_on macos: ">= :big_sur"

  app "Shannon Desktop.app"

  zap trash: [
    "~/Library/Application Support/shannon-desktop",
    "~/Library/Caches/shannon-desktop",
    "~/Library/Preferences/com.shannon-agent.desktop.plist",
    "~/Library/Saved Application State/com.shannon-agent.desktop.savedState",
  ]

  license "Apache-2.0"
end
