# Homebrew Formula for the Shannon Gateway binary.
# NOTE: This Formula is NOT auto-generated by cargo-dist — it is maintained by hand
# under the tap `shannon-agent/homebrew-shannon`.
# Asset URLs/versions/sha256 are filled at release time (CI / `brew bump-formula-pr`).
# Replace `#{version}` and the target suffix at release time.

class ShannonGateway < Formula
  version "0.7.0" # REPLACE AT RELEASE TIME — CI fills the real version.
  desc "Gateway service for the Shannon Agent"
  homepage "https://github.com/shannon-agent/shannon-agent"
  license "Apache-2.0"
  url "https://github.com/shannon-agent/shannon-agent/releases/download/v#{version}/shannon-gateway-darwin-x64"
  sha256 "" # REPLACE AT RELEASE TIME with the real sha256 of the downloaded binary.

  # Linux/Windows variants (pick one `url`/`sha256` per platform at release time):
  #   linux-x64:   https://github.com/shannon-agent/shannon-agent/releases/download/v#{version}/shannon-gateway-linux-x64
  #   linux-arm64: https://github.com/shannon-agent/shannon-agent/releases/download/v#{version}/shannon-gateway-linux-arm64
  #   darwin-arm64: https://github.com/shannon-agent/shannon-agent/releases/download/v#{version}/shannon-gateway-darwin-arm64

  livecheck do
    url "https://github.com/shannon-agent/shannon-agent/releases/latest"
    regex(/v?(\d+(?:\.\d+)+)/i)
  end

  def install
    bin.install "shannon-gateway-darwin-x64" => "shannon-gateway"
    # For non-macOS targets, rename the downloaded binary to "shannon-gateway":
    #   bin.install "shannon-gateway-linux-x64" => "shannon-gateway"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/shannon-gateway --version")
  end
end
