//! Build script for `shannon-desktop`.
//!
//! Historical note (P1-1 recon, 2026-09): this script used to be a no-op —
//! `tauri_build::build()` never ran, so `tauri-codegen` compiled
//! `generate_context!` with an *empty* ACL (no `acl-manifests.json` and no
//! `capabilities.json` in `OUT_DIR`). Consequences of that state:
//!
//! - the app's own Tauri commands are **not** ACL-gated at all (no
//!   `__app-acl__` manifest ⇒ `RuntimeAuthority::has_app_manifest()` is
//!   false ⇒ local-origin invokes of app commands bypass the check), and
//! - **every** `plugin:*` command — including the JS event API
//!   (`plugin:event|listen`) and window APIs (`plugin:window|set-title`) —
//!   was denied on every window, because an empty resolved ACL allows
//!   nothing.
//!
//! We cannot simply call `tauri_build::build()` here: it also copies the
//! `bundle.externalBin` sidecar (`binaries/shannon-<target-triple>`), which
//! is gitignored and absent on fresh clones/CI, so the whole crate build
//! would fail there. Instead this script implements the *minimal* slice of
//! `tauri-build` that the P1-1 multi-window feature needs:
//!
//! 1. if `capabilities/*.json` exists, build **minimal** ACL manifests for
//!    the core plugins those capabilities reference (currently
//!    `core:event` + `core:window` + `core:app` + `core:path`),
//! 2. validate the capabilities against those manifests (fail-fast, same
//!    semantics as `tauri-build`'s `validate_capabilities`),
//! 3. write `acl-manifests.json` + `capabilities.json` into `OUT_DIR`,
//!    which is exactly where `tauri-codegen` expects them.
//!
//! review §P2-21 (2026-09): the application-level ACL is now landed. The
//! `__app-acl__` manifest is generated from `acl/app-permissions.json`
//! (one `allow-<command>` permission per `generate_handler!` command,
//! grouped into `app-*` permission sets — the same naming scheme
//! `tauri-build` autogenerates for plugins). Its presence flips
//! `RuntimeAuthority::has_app_manifest()` to true, so **every** invoke —
//! app command or plugin command — is checked against the resolved ACL:
//! default posture is deny, and only windows matching a capability's
//! `windows` globs (`main`, `session-*`) on the local origin get grants.
//! The `desktop/tests/app_command_acl_coverage.rs` +
//! `desktop/tests/session_window_acl.rs` tests are the safety net: they
//! re-derive the command inventory from `main.rs` and fail the build if a
//! command is added without a matching ACL entry.
//!
//! Still deliberately **not** done here (and why):
//! - no sidecar/resource copying, no Windows resources: those belong to the
//!   full `tauri_build::build()`, which can replace this once the sidecar
//!   staging problem is solved upstream of this task.
#![cfg_attr(not(feature = "tauri"), allow(unused))]

fn main() {
    #[cfg(feature = "tauri")]
    shannon_desktop_build::emit_acl_if_capabilities_present();
}

#[cfg(feature = "tauri")]
mod shannon_desktop_build {
    use std::collections::BTreeMap;
    use std::path::{Path, PathBuf};

    use tauri_utils::acl::capability::{Capability, CapabilityFile};
    use tauri_utils::acl::manifest::{Manifest, PermissionFile};
    use tauri_utils::acl::resolved::Resolved;
    use tauri_utils::acl::{APP_ACL_KEY, Commands, Permission, PermissionSet};
    use tauri_utils::platform::Target;

    const CAPABILITIES_DIR: &str = "capabilities";
    const ACL_MANIFESTS_FILE: &str = "acl-manifests.json";
    const CAPABILITIES_FILE: &str = "capabilities.json";
    /// Application permission file (review §P2-21): one `allow-<command>`
    /// permission per `generate_handler!` command plus `app-*` permission
    /// sets. Parsed as tauri-utils' `PermissionFile` and published under the
    /// `__app-acl__` manifest key, which is how `tauri-codegen` discovers
    /// the app-level ACL. Maintained together with
    /// `desktop/tests/app_command_acl_coverage.rs`, which fails when a new
    /// command lacks an entry here.
    const APP_ACL_PERMISSIONS_FILE: &str = "acl/app-permissions.json";

    /// Minimal manifest for `core:event`, mirroring the upstream
    /// autogenerated default (listen/unlisten/emit/emit_to — the JS event
    /// API used by `@tauri-apps/api/event`). Only what our capabilities
    /// reference; extending requires adding entries here.
    fn core_event_manifest() -> Manifest {
        let mut m = Manifest {
            default_permission: None,
            permissions: BTreeMap::new(),
            permission_sets: BTreeMap::new(),
            global_scope_schema: None,
        };
        for (name, cmd, desc) in [
            (
                "allow-listen",
                "listen",
                "This permission allows listening to all events.",
            ),
            (
                "allow-unlisten",
                "unlisten",
                "This permission allows unlistening to all events.",
            ),
            (
                "allow-emit",
                "emit",
                "This permission allows emitting an event to all targets.",
            ),
            // Permission names are kebab-case upstream; the *command* stays
            // `emit_to` (the IPC name the JS API invokes).
            (
                "allow-emit-to",
                "emit_to",
                "This permission allows emitting an event to a specific target.",
            ),
        ] {
            m.permissions.insert(
                name.to_string(),
                Permission {
                    version: None,
                    identifier: name.to_string(),
                    description: Some(desc.to_string()),
                    commands: Commands {
                        allow: vec![cmd.to_string()],
                        deny: vec![],
                    },
                    scope: Default::default(),
                    platforms: None,
                },
            );
        }
        m.default_permission = Some(PermissionSet {
            identifier: "default".into(),
            description:
                "Default permissions for the plugin. Allows listening and emitting events.".into(),
            permissions: vec![
                "core:event:allow-listen".into(),
                "core:event:allow-unlisten".into(),
                "core:event:allow-emit".into(),
                "core:event:allow-emit-to".into(),
            ],
        });
        m
    }

    /// Minimal manifest for `core:window`: only `allow-set-title` (session
    /// windows keep their title in sync with the session title). Note that
    /// `core:window:default` resolves to an *empty* permission set here —
    /// capabilities must reference `core:window:allow-set-title` explicitly.
    fn core_window_manifest() -> Manifest {
        let mut m = Manifest {
            default_permission: None,
            permissions: BTreeMap::new(),
            permission_sets: BTreeMap::new(),
            global_scope_schema: None,
        };
        m.permissions.insert(
            "allow-set-title".to_string(),
            Permission {
                version: None,
                identifier: "allow-set-title".to_string(),
                description: Some("This permission allows setting the window title.".to_string()),
                commands: Commands {
                    allow: vec!["set_title".to_string()],
                    deny: vec![],
                },
                scope: Default::default(),
                platforms: None,
            },
        );
        m
    }

    /// Minimal manifest for the `dialog` plugin (review §P1-11): exposes
    /// only the two verbs the desktop frontend actually uses —
    /// `allow-open` (file / directory pickers) and `allow-save` (artifact /
    /// session / persona-pack exports). Without this manifest the
    /// `file-dialogs.json` capability we ship would fail resolution and
    /// the @tauri-apps/plugin-dialog calls would 403 at runtime, leaving
    /// the user with a toast instead of the picker UI.
    fn dialog_manifest() -> Manifest {
        let mut m = Manifest {
            default_permission: None,
            permissions: BTreeMap::new(),
            permission_sets: BTreeMap::new(),
            global_scope_schema: None,
        };
        let allow_open = Permission {
            version: None,
            identifier: "allow-open".to_string(),
            description: Some("Allows opening a file/directory picker dialog.".to_string()),
            commands: Commands {
                allow: vec!["open".to_string()],
                deny: vec![],
            },
            scope: Default::default(),
            platforms: None,
        };
        let allow_save = Permission {
            version: None,
            identifier: "allow-save".to_string(),
            description: Some("Allows opening a save file dialog.".to_string()),
            commands: Commands {
                allow: vec!["save".to_string()],
                deny: vec![],
            },
            scope: Default::default(),
            platforms: None,
        };
        m.permissions.insert("allow-open".to_string(), allow_open);
        m.permissions.insert("allow-save".to_string(), allow_save);
        m
    }

    /// Minimal manifest for the `core:app` plugin: only `allow-version`
    /// (the Advanced settings card shows the real app version — the old fake
    /// logs modal hardcoded one). The IPC command is `plugin:app|version`.
    fn core_app_manifest() -> Manifest {
        let mut m = Manifest {
            default_permission: None,
            permissions: BTreeMap::new(),
            permission_sets: BTreeMap::new(),
            global_scope_schema: None,
        };
        m.permissions.insert(
            "allow-version".to_string(),
            Permission {
                version: None,
                identifier: "allow-version".to_string(),
                description: Some(
                    "This permission allows reading the app's version string.".to_string(),
                ),
                commands: Commands {
                    allow: vec!["version".to_string()],
                    deny: vec![],
                },
                scope: Default::default(),
                platforms: None,
            },
        );
        m
    }

    /// Minimal manifest for the `core:path` plugin: only the two verbs the
    /// frontend needs to locate the Shannon state directory for the
    /// 「open log directory」entry — `allow-home-dir` (`plugin:path|homedir`)
    /// and `allow-join` (`plugin:path|join`). Read-only path helpers with no
    /// filesystem access of their own.
    fn core_path_manifest() -> Manifest {
        let mut m = Manifest {
            default_permission: None,
            permissions: BTreeMap::new(),
            permission_sets: BTreeMap::new(),
            global_scope_schema: None,
        };
        for (name, cmd, desc) in [
            (
                "allow-home-dir",
                "homedir",
                "This permission allows reading the user's home directory path.",
            ),
            (
                "allow-join",
                "join",
                "This permission allows joining path segments.",
            ),
        ] {
            m.permissions.insert(
                name.to_string(),
                Permission {
                    version: None,
                    identifier: name.to_string(),
                    description: Some(desc.to_string()),
                    commands: Commands {
                        allow: vec![cmd.to_string()],
                        deny: vec![],
                    },
                    scope: Default::default(),
                    platforms: None,
                },
            );
        }
        m
    }

    /// Loads the application-level ACL manifest (review §P2-21) from
    /// `acl/app-permissions.json`. The file uses tauri-utils'
    /// [`PermissionFile`] layout (the same shape the tauri CLI's
    /// `autogenerate_command_permissions` emits for plugins), so
    /// [`Manifest::new`] performs the permission/set flattening exactly as
    /// upstream would. Published under [`APP_ACL_KEY`] so
    /// `RuntimeAuthority::has_app_manifest()` sees it and the invoke
    /// dispatcher starts ACL-checking app commands.
    fn app_acl_manifest() -> Result<Manifest, String> {
        let path = Path::new(APP_ACL_PERMISSIONS_FILE);
        let contents = std::fs::read_to_string(path)
            .map_err(|e| format!("failed to read {}: {e}", path.display()))?;
        let file: PermissionFile = serde_json::from_str(&contents)
            .map_err(|e| format!("failed to parse {}: {e}", path.display()))?;
        Ok(Manifest::new(vec![file], None))
    }

    fn load_capabilities(dir: &Path) -> Result<Vec<Capability>, String> {
        let mut entries = Vec::new();
        let mut files: Vec<PathBuf> = std::fs::read_dir(dir)
            .map_err(|e| format!("failed to read {}: {e}", dir.display()))?
            .filter_map(|e| e.ok().map(|e| e.path()))
            .filter(|p| p.extension().map(|e| e == "json").unwrap_or(false))
            .collect();
        files.sort();
        for file in files {
            match CapabilityFile::load(&file) {
                Ok(CapabilityFile::Capability(c)) => entries.push(c),
                Ok(CapabilityFile::List(list)) => entries.extend(list),
                Ok(CapabilityFile::NamedList { capabilities }) => entries.extend(capabilities),
                Err(e) => return Err(format!("failed to load {}: {e}", file.display())),
            }
        }
        Ok(entries)
    }

    /// Emits `acl-manifests.json` + `capabilities.json` into `OUT_DIR` when
    /// the package has a non-empty `capabilities/` directory. No-op when it
    /// does not exist (preserves the historical empty-ACL build).
    pub fn emit_acl_if_capabilities_present() {
        let dir = Path::new(CAPABILITIES_DIR);
        println!("cargo:rerun-if-changed=build.rs");
        if !dir.is_dir() {
            return;
        }
        println!("cargo:rerun-if-changed={CAPABILITIES_DIR}/**/*");
        println!("cargo:rerun-if-changed={APP_ACL_PERMISSIONS_FILE}");

        let capabilities = load_capabilities(dir).unwrap_or_else(|e| panic!("{e}"));
        if capabilities.is_empty() {
            return;
        }

        let mut manifests: BTreeMap<String, Manifest> = BTreeMap::new();
        manifests.insert("core:event".into(), core_event_manifest());
        manifests.insert("core:window".into(), core_window_manifest());
        manifests.insert("core:app".into(), core_app_manifest());
        manifests.insert("core:path".into(), core_path_manifest());
        manifests.insert("dialog".into(), dialog_manifest());
        // review §P2-21 — the application manifest. Once this key exists in
        // the emitted acl-manifests.json, `generate_context!` bakes
        // `has_app_acl = true` into the runtime authority and *every*
        // invoke (app + plugin) is ACL-checked on window label / origin.
        manifests.insert(
            APP_ACL_KEY.to_string(),
            app_acl_manifest().unwrap_or_else(|e| panic!("{e}")),
        );

        // Fail fast with upstream-identical semantics: resolve the ACL the
        // same way tauri-codegen will at macro expansion. An unknown
        // permission/manifest name aborts the build here with a readable
        // message instead of a proc-macro panic later.
        let mut capability_map: BTreeMap<String, Capability> = BTreeMap::new();
        for capability in capabilities {
            if capability_map
                .insert(capability.identifier.clone(), capability)
                .is_some()
            {
                panic!("duplicate capability identifier in {CAPABILITIES_DIR}/");
            }
        }
        let target = Target::from_triple(&std::env::var("TARGET").unwrap());
        Resolved::resolve(&manifests, capability_map.clone(), target)
            .unwrap_or_else(|e| panic!("failed to resolve ACL from {CAPABILITIES_DIR}/: {e}"));

        let out_dir = PathBuf::from(std::env::var_os("OUT_DIR").unwrap());
        write_if_changed(
            &out_dir.join(ACL_MANIFESTS_FILE),
            &serde_json::to_string(&manifests).expect("serialize acl-manifests.json"),
        );
        write_if_changed(
            &out_dir.join(CAPABILITIES_FILE),
            &serde_json::to_string(&capability_map).expect("serialize capabilities.json"),
        );
    }

    fn write_if_changed(path: &Path, contents: &str) {
        if std::fs::read_to_string(path).is_ok_and(|existing| existing == contents) {
            return;
        }
        std::fs::write(path, contents).unwrap_or_else(|e| {
            panic!("failed to write {}: {e}", path.display());
        });
    }
}
