//! Build script for `shannon-desktop`.
//!
//! Historical note (P1-1 recon, 2026-09): this script used to be a no-op —
//! `tauri_build::build()` never ran, so `tauri-codegen` compiled
//! `generate_context!` with an *empty* ACL (no `acl-manifests.json` and no
//! `capabilities.json` in `OUT_DIR`). Consequences of that state:
//!
//! - the app's own Tauri commands are **not** ACL-gated at all (no
//!   `__app-acl__` manifest ⇒ `RuntimeAuthority::has_app_manifest()` is
//!   false ⇒ local-origin invokes of app commands bypass the check), and
//! - **every** `plugin:*` command — including the JS event API
//!   (`plugin:event|listen`) and window APIs (`plugin:window|set-title`) —
//!   was denied on every window, because an empty resolved ACL allows
//!   nothing.
//!
//! We cannot simply call `tauri_build::build()` here: it also copies the
//! `bundle.externalBin` sidecar (`binaries/shannon-<target-triple>`), which
//! is gitignored and absent on fresh clones/CI, so the whole crate build
//! would fail there. Instead this script implements the *minimal* slice of
//! `tauri-build` that the P1-1 multi-window feature needs:
//!
//! 1. if `capabilities/*.json` exists, build **minimal** ACL manifests for
//!    the core plugins those capabilities reference (currently
//!    `core:event` + `core:window`),
//! 2. validate the capabilities against those manifests (fail-fast, same
//!    semantics as `tauri-build`'s `validate_capabilities`),
//! 3. write `acl-manifests.json` + `capabilities.json` into `OUT_DIR`,
//!    which is exactly where `tauri-codegen` expects them.
//!
//! With no capabilities directory nothing is written and the compile-time
//! behaviour is identical to the historical no-op build script.
//!
//! Deliberately **not** done here (and why):
//! - no `__app-acl__` manifest: writing one would flip
//!   `has_app_acl_manifest` to true and start ACL-gating all ~200 existing
//!   app commands, breaking every window;
//! - no sidecar/resource copying, no Windows resources: those belong to the
//!   full `tauri_build::build()`, which can replace this once the sidecar
//!   staging problem is solved upstream of this task.
#![cfg_attr(not(feature = "tauri"), allow(unused))]

fn main() {
    #[cfg(feature = "tauri")]
    shannon_desktop_build::emit_acl_if_capabilities_present();
}

#[cfg(feature = "tauri")]
mod shannon_desktop_build {
    use std::collections::BTreeMap;
    use std::path::{Path, PathBuf};

    use tauri_utils::acl::capability::{Capability, CapabilityFile};
    use tauri_utils::acl::manifest::Manifest;
    use tauri_utils::acl::resolved::Resolved;
    use tauri_utils::acl::{Commands, Permission, PermissionSet};
    use tauri_utils::platform::Target;

    const CAPABILITIES_DIR: &str = "capabilities";
    const ACL_MANIFESTS_FILE: &str = "acl-manifests.json";
    const CAPABILITIES_FILE: &str = "capabilities.json";

    /// Minimal manifest for `core:event`, mirroring the upstream
    /// autogenerated default (listen/unlisten/emit/emit_to — the JS event
    /// API used by `@tauri-apps/api/event`). Only what our capabilities
    /// reference; extending requires adding entries here.
    fn core_event_manifest() -> Manifest {
        let mut m = Manifest {
            default_permission: None,
            permissions: BTreeMap::new(),
            permission_sets: BTreeMap::new(),
            global_scope_schema: None,
        };
        for (name, cmd, desc) in [
            ("allow-listen", "listen", "This permission allows listening to all events."),
            ("allow-unlisten", "unlisten", "This permission allows unlistening to all events."),
            ("allow-emit", "emit", "This permission allows emitting an event to all targets."),
            // Permission names are kebab-case upstream; the *command* stays
            // `emit_to` (the IPC name the JS API invokes).
            ("allow-emit-to", "emit_to", "This permission allows emitting an event to a specific target."),
        ] {
            m.permissions.insert(
                name.to_string(),
                Permission {
                    version: None,
                    identifier: name.to_string(),
                    description: Some(desc.to_string()),
                    commands: Commands { allow: vec![cmd.to_string()], deny: vec![] },
                    scope: Default::default(),
                    platforms: None,
                },
            );
        }
        m.default_permission = Some(PermissionSet {
            identifier: "default".into(),
            description: "Default permissions for the plugin. Allows listening and emitting events.".into(),
            permissions: vec![
                "core:event:allow-listen".into(),
                "core:event:allow-unlisten".into(),
                "core:event:allow-emit".into(),
                "core:event:allow-emit-to".into(),
            ],
        });
        m
    }

    /// Minimal manifest for `core:window`: only `allow-set-title` (session
    /// windows keep their title in sync with the session title). Note that
    /// `core:window:default` resolves to an *empty* permission set here —
    /// capabilities must reference `core:window:allow-set-title` explicitly.
    fn core_window_manifest() -> Manifest {
        let mut m = Manifest {
            default_permission: None,
            permissions: BTreeMap::new(),
            permission_sets: BTreeMap::new(),
            global_scope_schema: None,
        };
        m.permissions.insert(
            "allow-set-title".to_string(),
            Permission {
                version: None,
                identifier: "allow-set-title".to_string(),
                description: Some(
                    "This permission allows setting the window title.".to_string(),
                ),
                commands: Commands {
                    allow: vec!["set_title".to_string()],
                    deny: vec![],
                },
                scope: Default::default(),
                platforms: None,
            },
        );
        m
    }

    fn load_capabilities(dir: &Path) -> Result<Vec<Capability>, String> {
        let mut entries = Vec::new();
        let mut files: Vec<PathBuf> = std::fs::read_dir(dir)
            .map_err(|e| format!("failed to read {}: {e}", dir.display()))?
            .filter_map(|e| e.ok().map(|e| e.path()))
            .filter(|p| p.extension().map(|e| e == "json").unwrap_or(false))
            .collect();
        files.sort();
        for file in files {
            match CapabilityFile::load(&file) {
                Ok(CapabilityFile::Capability(c)) => entries.push(c),
                Ok(CapabilityFile::List(list)) => entries.extend(list),
                Ok(CapabilityFile::NamedList { capabilities }) => entries.extend(capabilities),
                Err(e) => return Err(format!("failed to load {}: {e}", file.display())),
            }
        }
        Ok(entries)
    }

    /// Emits `acl-manifests.json` + `capabilities.json` into `OUT_DIR` when
    /// the package has a non-empty `capabilities/` directory. No-op when it
    /// does not exist (preserves the historical empty-ACL build).
    pub fn emit_acl_if_capabilities_present() {
        let dir = Path::new(CAPABILITIES_DIR);
        println!("cargo:rerun-if-changed=build.rs");
        if !dir.is_dir() {
            return;
        }
        println!("cargo:rerun-if-changed={CAPABILITIES_DIR}/**/*");

        let capabilities = load_capabilities(dir).unwrap_or_else(|e| panic!("{e}"));
        if capabilities.is_empty() {
            return;
        }

        let mut manifests: BTreeMap<String, Manifest> = BTreeMap::new();
        manifests.insert("core:event".into(), core_event_manifest());
        manifests.insert("core:window".into(), core_window_manifest());

        // Fail fast with upstream-identical semantics: resolve the ACL the
        // same way tauri-codegen will at macro expansion. An unknown
        // permission/manifest name aborts the build here with a readable
        // message instead of a proc-macro panic later.
        let mut capability_map: BTreeMap<String, Capability> = BTreeMap::new();
        for capability in capabilities {
            if capability_map
                .insert(capability.identifier.clone(), capability)
                .is_some()
            {
                panic!("duplicate capability identifier in {CAPABILITIES_DIR}/");
            }
        }
        let target = Target::from_triple(&std::env::var("TARGET").unwrap());
        Resolved::resolve(&manifests, capability_map.clone(), target)
            .unwrap_or_else(|e| panic!("failed to resolve ACL from {CAPABILITIES_DIR}/: {e}"));

        let out_dir = PathBuf::from(std::env::var_os("OUT_DIR").unwrap());
        write_if_changed(
            &out_dir.join(ACL_MANIFESTS_FILE),
            &serde_json::to_string(&manifests).expect("serialize acl-manifests.json"),
        );
        write_if_changed(
            &out_dir.join(CAPABILITIES_FILE),
            &serde_json::to_string(&capability_map).expect("serialize capabilities.json"),
        );
    }

    fn write_if_changed(path: &Path, contents: &str) {
        if std::fs::read_to_string(path).is_ok_and(|existing| existing == contents) {
            return;
        }
        std::fs::write(path, contents).unwrap_or_else(|e| {
            panic!("failed to write {}: {e}", path.display());
        });
    }
}
