fn main() {
    // When the `tauri` feature is enabled, the tauri-build dependency is
    // pulled in and the build script generated by tauri_build::build()
    // runs instead of this file (Cargo replaces build.rs with the generated
    // one).  Without the feature, this no-op build script is used.
    println!("cargo:rerun-if-changed=build.rs");
}
